### PR TITLE
Added Cheese's Newsletters

### PR DESCRIPTION
**Pull request by CheeseLad**
Added all of my newsletters built with my announce redbrick lists web scraper

### CODE REVIEW

**Review by JedHazaymeh — COMMENTED** [review]
Can we move the newsletters up a level to the root dir?
Otherwise, LGTM for now - will deploy a preview. Love the working images 🥇

**Comment by CheeseLad** [comment]
Yep can do, thank you :)

**Comment by JedHazaymeh** [comment]
Review deployment live: https://magma.redbrick.dcu.ie

**Review by JedHazaymeh — CHANGES_REQUESTED** [review]
I reckon we should rename the title of each from, for example:
`Week 12 Newsletter -> 22/23 Semester 2 Week 12`.

Since we are in the newsletters folder (and soon, the newsletter tag), having "newsletter" repeated is sort of redundant. If we can change that, we're good to go!

**Review by JedHazaymeh — APPROVED** [review]
LGTM 🚀

**Pull request merged**
